[package]
name = "shifting-renderer-ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shifting-core = { path="../shifting-core"}
ggez = "0.7.0"
mint = "0.5.9"
image = "0.23.14"